apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-deployment
  labels:
    app: my-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-todo
  template:
    metadata:
      labels:
        app: my-todo
    spec:
      containers:
        - name: todo-app-container
          image: sumyth13/todo-app:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80          # The port exposed by the Service
      targetPort: 8080  # The port on the Pod to send the traffic to
      nodePort: 30007   # The port on each Node to expose externally
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-todo-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
